## Annotation
# [[motif, name, function], ..., [motif, name, function]]
db_motif = [[r'PP.R', 'bact5', 'proline rich, gram+, protein synthesis blocking'],
            [r'PPR.', 'bact7', 'proline rich, gram+, protein synthesis blocking'],
            [r'RW', 'ion-pair-pi', 'enhanced protein-membrane interaction, gram+/-'],
            [r'GG', 'gly-central–symmetrical', 'activates phagocyte-mediated microbicidal mechanisms, gram-'],
            [r'(G|A|V|L|I|F|P|M|W){2,2}(R|K|H){2,2}', 'GALA', 'mimetics a-helix, gram+/-'],
            [r'L{,}K{,}[W]{2,2}', 'model pep LeuLysTrp', 'amphipathic interface between the hydrophilic ending side and the hydrophobic starting side, gram+'],
            [r'KLD', 'KLD12', 'self-assembly peptide, beta-sheet, membrane destability inducer, tends to dimer, low toxicity'],
            [r'(GGH|VIH)$', 'ATCUN', 'C-terminal, generate ROS after combining with Cu2+'],
            [r'CGL.GLC', 'Rana box', 'motif is important in determining bacteriostatic activity'],
            [r'G.WKRKRF.G$', 'lipid binding motif', 'induce broad spectrum of antibacterial activity'],
            [r'G.C.{3,9}', 'γ-core motif', 'directly involved in protein–membrane interactions and strongly contribute to membrane binding, antifungal'],
            [r'NGR', 'NGR motif', 'citotoxicity, NGR may bind to CD13+ or αvβ3+ tumor cells'],
            [r'G...G', 'Gly zipper', 'can induce strong self-assembly'],
            [r'RLLR', 'BfII', 'high potency, gram-'],
            [r'RRWQWR', 'LfcinB', 'broad spectrum'],
            [r'RGD*', 'RGD', 'integrin binding cell adhesion'],
            [r'FEANE', 'cagL', 'participates in integrin binding'],
            [r'LP.TG', 'cspA', 'Cell wall anchor motif'],
            [r'[SG][VI][AS][IVT]G..S', 'yadA', 'Repeated collagen binding motif'],
            [r'[LF]Y[DNK]...[KG][KV]Y[VD]*', 'Eno', 'plasminogen binding motif'],
            [r'W[WFY][FY]....G.M', 'CBP-A', 'Repeated cholin (cell wall) binding motif'],
            [r'YRNYPT', 'spsA', 'Host secretory immunglobulin A (SlgA) and secretory component (SC) binding motif'],
            [r'[DSTE][^P][^DEWHFYC]D[GSAN]', 'sopA', 'Caspase 3 cleavage site motif'],
            [r'^M{0,1}(G)[^EDRKHPFYW]..[STAGCN][^P]', 'N-myristoylation/S-palmitoylation motif', 'N-myristoylation/S-palmitoylation motif'],
            [r'W...E*', 'Rho GTPase', 'Host Rho GTPase activation/modulation motif'],
            [r'[LR][KQVS][KQLR][EST][GQR][FLKS][EGPK][MLVAS][KNAL][SGIE]*', 'wtsE', 'Putative endoplasmic reticulum membrane retention/retrieval motif'],
            [r'(C)[^DENQ][LIVM].$', 'CAAX box', 'putative prenylation motif (addition of farnesyl or geranylgeranyl group)'],
            [r'G.LR...T', 'Arginine finger motif', 'essential for Rho GAP function of virulence factors'],
            [r'[^DE]((K[RK])|(RK))[KRP][KR][^DE]', 'NLS_d', 'Nuclear localization signal (NLS) motif'],
            [r'[KR][KR].{7,15}[^DE]((K[KR])|(RK))(([^DE][KR])|(KR][^DE]))[^DE]', 'NLS_m', 'Nuclear localization signal (NLS) motif'],
            [r'[^DE]((K[RK])|(RK))(([^DE][KR])|([KR][^DE]))(([PKR])|([^DE][DE]))', 'NLS_p', 'Nuclear localization signal (NLS) motif'],
            [r'(([PKR].{0,1}[^DE])|([PKR]))((K[RK])|(RK))(([^DE][KR])|([KR][^DE]))[^DE]', 'NLS_x', 'Nuclear localization signal (NLS) motif'],
            [r'[KR]{0,2}[KR].{0,2}[KR].{2,4}[ILVM].[ILVF]', 'D motif', 'Docking motif required for specific binding to MAPKs'],
            [r'E[PNS][IV]Y[AEG]', 'MTPM', 'Membrane targeting/phosphorylation motif'],
            [r'PPASP*', 'PEST-motif', 'involved in phagosomal escape of bacteria in infected cells'],
            [r'GDK', 'Autoproteolytic cleavage motif', 'Autoproteolytic cleavage motif'],
            [r'GAG[AT]', 'guanine nucleotide exchange', 'Catalytic loop motif essential for guanine nucleotide exchange'],
            [r'KAWRN', 'kWARN', 'Plasma membrane localization/ubiquitinylation motif'],
            [r'WEK[IM]..FF', 'TLE target', 'Translocation/late endocytic compartments targeting motif'],
            [r'[FIV]..[FIV].[FIV]..[NC].[FIV]', 'Golgi_lock', 'Membrane localization motif (targets ExoS to the Golgi-endoplasmic reticulum)'],
            [r'L..AA..VA..V..LI..A.', 'Vinculin', 'Vinculin binding domain motif'],
            [r'LLDALDLA', 'FAS(14-3-3 protein) binding motif', 'mediates activation of the ADPRT domain'],
            [r'G....GK[TS]*', 'Walker A motif', 'nucleotide-binding motif'],
            [r'W.G', 'cargo', 'motif helps to create a shallow cleft structure and may represent a peptide recognition feature by which cargo proteins are acquired for transport'],                        
            [r'LSGGQ', 'ABC-motif', 'ATP binding cassette transporter motif'],
            [r'[RK]....G....L[VILFWYMC]{4,4}D', 'Walker B', 'nucleotide binding motif'],
            [r'^.K.{0,2}K', 'Adherence_1', 'Signal peptide motif'],
            [r'^.{1,2}K.{1,2}L', 'Adherence_1', 'Signal peptide motif'],
            [r'^.{1,2}K.{0,2}I', 'Adherence_1', 'Signal peptide motif'],
            [r'^.K.[IL]', 'Adherence_1', 'Signal peptide motif'],
            [r'^.K..S', 'Adherence_1', 'Signal peptide motif'],
            [r'^.{1,2}K.{0,1}I', 'Capsule_1', 'Signal peptide motif'],
            [r'^.{1,2}K.{0,1}I..V', 'Capsule_2', 'Signal peptide motif'],
            [r'^.{1,2}K.{0,2}I', 'Capsule_3', 'Signal peptide motif'],
            [r'^.K.[ILV]', 'Capsule_4', 'Signal peptide motif'],
            [r'^.{1,2}K.{0,2}K', 'Capsule_5', 'Signal peptide motif'],
            [r'^.{1,2}KK', 'Enzyme_l', 'Signal peptide motif'],
            [r'^..K.{0,2}I', 'Enzyme_w', 'Signal peptide motif'],
            [r'L.[AG]C[AGS]', 'Lipoprot_A', 'Lipobox'],
            [r'[FLV].L.[AG]C', 'Lipoprot_B', 'Lipobox'],
            [r'[ILV].[AGS]C', 'Lipoprot_C', 'Lipobox'],
            [r'[AGS]C[AGS]', 'Lipoprot_D', 'Lipobox'],
            [r'^.{1,2}K.{0,2}K', 'Lipoprot_E', 'Signal peptide motif'],
            [r'L.{1,2}GC.{0,1}A', 'Lipoprot_F', 'Lipobox'],
            [r'A.{0,2}L..C.{0,2}S', 'Lipoprot_G', 'Lipobox'],
            [r'^.K..[ILV]', 'Lipoprot_H', 'Signal peptide motif'],
            [r'^..K..[FLV]', 'Lipoprot_I', 'Signal peptide motif'],
            [r'[ILV]..C.[AGS]', 'Lipoprot_J', 'Lipobox'],
            [r'KK$', 'Lipoprot_K', 'C-terminal KK'],
            [r'^.[KR]I', 'siderophore_d', 'Signal peptide motif'],
            [r'^.K[KR]', 'typeIV_sec_I', 'Signal peptide motif'],
            [r'^.K..[FIL]', 'typeIV_secII', 'Signal peptide motif'],
            [r'LP.G.Y', 'adherence_to_surface', 'Adherence'],
            [r'G.S..M.L', 'capsule', 'Capsule'],
            [r'E..Q.I[AG].I', 'chemotaxis_1', 'Chemotaxis'],
            [r'E..Q.[IV]..I', 'chemotaxis_2', 'Chemotaxis'],
            [r'^..I.{0,1}N', 'effector_I', 'Effector'],
            [r'[LV].PY', 'effector_II', 'Effector'],
            [r'^..I[ST]', 'effector_III', 'Effector'],
            [r'A.I.P.VL', 'Enzyme_a', 'Enzyme'],
            [r'VSIL.S', 'Enzyme_b', 'Enzyme'],
            [r'ML..C', 'Lipoprotein', 'Lipoprotein'],
            [r'I.K..G', 'siderophore_b', 'Siderophore'],
            [r'GYP..TP', 'siderophore_a', 'Siderophore'],
            [r'G[AG].$', 'type IV', 'Type IV secretion'],
            ]

