import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter


# This file 'result_tax.txt' was generated by the script taxon_analysis.py
# loading data
data = pd.read_table('result_tax.txt')

# creating 
d = dict(Counter(data.taxonomy.str.capitalize()))
none = 863498 - sum(d.values())  # 863,498 is the total number of AMPs in AMPSphere
d['None'] = none

df = pd.DataFrame.from_dict(d,
                            orient='index',
                            columns=['AMP candidates']).loc[['None',
                                                             'Superkingdom',
                                                             'Phylum',
                                                             'Class',
                                                             'Order',
                                                             'Family',
                                                             'Genus',
                                                             'Species']]

df = df * 100 / df.sum()

df.T.plot.bar(stacked=True, cmap='Dark2')
plt.tight_layout()
plt.ylabel('AMPSphere candidates - %')
plt.savefig('taxonrank.svg')
